### PR TITLE
Different Changes for EnterpriseStorage and StorageSpaces

### PR DESCRIPTION
**Pull request by rolbre**
Mainchanges:
Add Support for German Account Names, e.g. Account 'Network Service' doesn´t exists on german Servers. Change Account Detection from Name to SID.

Remove log4net Logging from WebDavPortal and change it to the Logging-Feature a´la WebsitePanel Server

### CODE REVIEW

**Comment by Virtuworks** [comment]
You consider these bugs? Please explain further.

**Comment by rolbre** [comment]
I commented every Change/Fix in the Source-Code. Please view the Code then you will get details. For any other questions contact me. Thanks.

**Comment by Virtuworks** [comment]
I'm sorry, I don't have much time or read code. If you want it merged I need something to review. Please send to info@websitepanel.net.

**Comment by Virtuworks** [comment]
PS - Just a list of points you are addressing and why.

**Pull request merged**
