### PR TITLE
Hyper-V 2012 R2 minor fix

### PR DESCRIPTION
**Pull request by berkut1**
Delete default adapter after command New-VM

### CODE REVIEW

**Comment by Virtuworks** [comment]
Do you have a cla with outercurve?

**Comment by berkut1** [comment]
No, I don't have.

**Comment by Virtuworks** [comment]
Please request one at www.websitepanel.net

**Comment by Virtuworks** [comment]
Anything on cla?

**Comment by berkut1** [comment]
cla request filled from websitepanel site. (dataclub)

**Pull request merged**
